#!/bin/bash


go build -o app ./src

mkdir -p .etc
mkdir -p .usr
mkdir -p lib

cat <<EOF > .etc/ADM_origin.json
{"RECORDS":[{}],"REPOS":[{}],"REGS":[{}]}
EOF

sudo /bin/cp -rf ./debug_bin/config /root/.kube/config

sudo ./app attached

