#!/bin/bash

FILES="debug_amalgamate_config/*"
KUBECONFIG=""

i=0

for f in $FILES
do
    if [ "$i" -eq 0 ]; then
        ff="$(realpath $f)"
        KUBECONFIG="$ff"
    fi

    if [ "$i" -gt 0 ]; then
        ff="$(realpath $f)"
        KUBECONFIG="$KUBECONFIG:$ff"
    fi

    i=$((i+1))

done

export KUBECONFIG

kubectl config view --flatten > config.amld.raw

unset KUBECONFIG
