#!/bin/bash

nkletd(){


    while true
    do

        CHECK=$(pgrep ./nokubelet | grep "" -c)
        if [ $CHECK -eq 0 ]
        then
            nohup ./nokubelet "$@"
        fi 
        sleep 3

    done

}

nkletd "$@" >/dev/null &