#!/bin/bash

portforwardrunner(){


    while true
    do

        CHECK=$(pgrep kubectl | grep "" -c)
        if [ $CHECK -eq 0 ]
        then
            kubectl port-forward svc/kube-prometheus-stack-prometheus 9090:9090 
        fi 
        sleep 3

    done

}

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

helm repo update  

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 45.29.0

portforwardrunner >/dev/null &