#!/bin/bash

./debug_amalgamate_bin/amalgamate

go run ./debug_amalgamate_bin/amalgamate.go

rm config.amld.raw

cp config.amld odb/config.amld

rm config.amld

cp okey osock/okey

rm okey

go build -o ./ofront/ofront ./ofront/.

go build -o ./osock/osock ./osock/.

sudo /bin/cp -rf ./debug_amalgamate_config/config2 /root/.kube/config

sudo docker-compose up --build