#!/bin/bash

portforwardrunner(){


    while true
    do

        CHECK=$(pgrep kubectl | grep "" -c)
        if [ $CHECK -eq 0 ]
        then
            kubectl port-forward svc/kube-prometheus-stack-prometheus 9090:9090 
        fi 
        sleep 3

    done

}

portforwardrunner >/dev/null &